# Define a custom bridge network for communication between containers
networks:
  network:
    driver: bridge

services:
  # Nginx service for serving web content
  nginx:
    container_name: nginx
    tty: true
    image: nginx
    restart: unless-stopped
    depends_on:
      - php
    volumes:
      - ./:/var/www/html:cached
      - ./.docker/nginx:/etc/nginx/conf.d
    ports:
      - "8000:80"
    networks:
      - network

  # PHP-FPM service for processing PHP code
  php:
    container_name: php
    tty: true
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html:cached
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - network

  # Node service for frontend
  node:
    container_name: node
    build:
      context: ./.docker/node
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./:/var/www/html:cached
    networks:
      - network

  # MySQL service for the database
  mysql:
    container_name: mysql
    tty: true
    image: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.docker/database:/var/lib/mysql
    networks:
      - network

  # phpMyAdmin for database management
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: pass
    ports:
      - "8030:80"
    depends_on:
      - mysql
    networks:
      - network

  # Mailpit service for email testing
  mailpit:
    container_name: mailPit
    tty: true
    image: axllent/mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
    networks:
      - network
