# Define a custom bridge network for communication between containers
networks:
  network:
    driver: bridge

services:
  # MySQL service for the database
  mysql:
    container_name: mysql
    tty: true
    image: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - network
