# Define a custom bridge network for communication between containers
networks:
  network:
    driver: bridge

services:
  # PostgreSQL service for the database
  postgres:
    container_name: postgres
    tty: true
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - network
