# Define a custom bridge network for communication between containers
networks:
  network:
    driver: bridge

services:
  # Redis service for caching and message broker
  redis:
    container_name: redis
    tty: true
    image: redis
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - "6379:6379"
    expose:
      - 6379
    networks:
      - network
